### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by jhurliman** [albertdb/node-zstandard#2]
Could this project bundle and make use of an OSX binary as well?

**Comment by albertdb** [comment]
Of course, but I don't have an OSX machine to build and test the OSX binary. If you could provide it, feel free to do a pull request after adding it to `bin` directory with filename `zstd.macos` or something like that. You can test it works by replacing `zstd.linux64` binary, as the code assumes that an OS that is not Windows is Linux.

**Comment by luke3butler** [comment]
A lot of us OSX users use brew to manage and update our zstd installation, so would it be possible to use the following to figure out if it's available?

`if(process.platform === "darwin") {`
`cp.exec('which zstd', function (error, stdout, stderr) {`
`console.log( (error !== null) ? "zstd does not exist" : "zstd exists on this macOS installation" );`
`});`
`}`

Edit: Either way, I created a PR with the darwin binary. I replaced the .linux64 with the one provided and didn't run into any bugs during my tests.

**Comment by jhurliman** [comment]
Personally, I'd prefer if a bundled binary was used over a system binary. There's no way to control what version of `zstd` people will have installed locally, so no way to guarantee requiring a specific version of `node-zstandard` will execute a specific version of `zstd` at runtime.

Thanks for submitting this! Looking forward to being able to use it on OSX.

**Comment by albertdb** [comment]
I agree with @jhurliman. I've merged the pull request, later on I will perform the minor modifications required. Thanks for providing the binary.

**Comment by albertdb** [comment]
Done.

**Comment by albertdb** [comment]
Hi @jhurliman and @luke3butler 

I'm planning to release a new version with zstd 1.4.0 bundled. Could anyone of you please provide an OSX binary for this version?

Thanks!

**Comment by luke3butler** [comment]
@albertdb Done. #7
